# Generated by Django 2.2.4 on 2019-12-10 03:48

import datetime
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='cidadeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liberacao', models.CharField(choices=[('1', 'Ativa'), ('2', 'Bloqueada'), ('3', 'Inativa')], default='1', max_length=2)),
                ('nome', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.CharField(choices=[('01', 'Acre (AC)'), ('02', 'Alagoas (AL)'), ('03', 'Amapá (AP)'), ('04', 'Amazonas (AM)'), ('05', 'Bahia (BA)'), ('06', 'Ceará (CE)'), ('07', 'Distrito Federal (DF)'), ('08', 'Espírito Santo (ES)'), ('09', 'Goiás (GO)'), ('10', 'Maranhão (MA)'), ('11', 'Mato Grosso (MT)'), ('12', 'Mato Grosso do Sul (MS)'), ('13', 'Minas Gerais (MG)'), ('14', 'Pará (PA)'), ('15', 'Paraíba (PB)'), ('16', 'Paraná (PR)'), ('17', 'Pernambuco (PE)'), ('18', 'Piauí (PI)'), ('19', 'Rio de Janeiro (RJ)'), ('20', 'Rio Grande do Norte (RN)'), ('21', 'Rio Grande do Sul (RS)'), ('22', 'Rondônia (RO)'), ('23', 'Roraima (RR)'), ('24', 'Santa Catarina (SC)'), ('25', 'São Paulo (SP)'), ('26', 'Sergipe (SE)'), ('27', 'Tocantins (TO)')], default='12', max_length=2)),
                ('dataCadastro', models.DateTimeField(default=datetime.datetime(2019, 12, 10, 3, 48, 38, 888847, tzinfo=utc))),
            ],
        ),
        migrations.CreateModel(
            name='salaModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liberacao', models.CharField(choices=[('1', 'Ativa'), ('2', 'Bloqueada'), ('3', 'Inativa')], default=1, max_length=1)),
                ('nome', models.CharField(blank=True, max_length=300, null=True)),
                ('localizacao', models.CharField(blank=True, max_length=300, null=True)),
                ('capacidade', models.CharField(blank=True, max_length=3, null=True)),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('cidadeEstado', models.ForeignKey(on_delete='models.CASCADE', to='gerencia.cidadeModel')),
            ],
        ),
        migrations.CreateModel(
            name='colaboradorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liberacao', models.CharField(choices=[('1', 'Ativo'), ('2', 'Bloqueado'), ('3', 'Inativo')], default=1, max_length=1)),
                ('nome', models.CharField(blank=True, max_length=300, null=True)),
                ('sobrenome', models.CharField(blank=True, max_length=400, null=True)),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('rg', models.CharField(blank=True, max_length=15, null=True)),
                ('endereco', models.CharField(blank=True, max_length=400, null=True)),
                ('numero', models.CharField(blank=True, max_length=5, null=True)),
                ('bairro', models.CharField(blank=True, max_length=200, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('telefone', models.CharField(blank=True, max_length=14, null=True)),
                ('celular', models.CharField(blank=True, max_length=14, null=True)),
                ('dataNasc', models.DateTimeField(default=datetime.datetime(2019, 12, 10, 3, 48, 38, 889691, tzinfo=utc))),
                ('cidadeEstado', models.ForeignKey(on_delete='models.CASCADE', to='gerencia.cidadeModel')),
                ('user', models.OneToOneField(on_delete='models.CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='alunoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liberacao', models.CharField(choices=[('1', 'Ativo'), ('2', 'Bloqueado'), ('3', 'Inativo')], default=1, max_length=1)),
                ('nome', models.CharField(blank=True, max_length=300, null=True)),
                ('sobrenome', models.CharField(blank=True, max_length=400, null=True)),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
                ('cpf', models.CharField(blank=True, max_length=14, null=True)),
                ('rg', models.CharField(blank=True, max_length=15, null=True)),
                ('endereco', models.CharField(blank=True, max_length=400, null=True)),
                ('numero', models.CharField(blank=True, max_length=5, null=True)),
                ('bairro', models.CharField(blank=True, max_length=200, null=True)),
                ('cep', models.CharField(blank=True, max_length=10, null=True)),
                ('telefone', models.CharField(blank=True, max_length=14, null=True)),
                ('celular', models.CharField(blank=True, max_length=14, null=True)),
                ('dataNasc', models.DateTimeField(default=django.utils.timezone.now)),
                ('cidadeEstado', models.ForeignKey(on_delete='models.CASCADE', to='gerencia.cidadeModel')),
                ('salaAula', models.ForeignKey(on_delete='models.CASCADE', to='gerencia.salaModel')),
                ('user', models.OneToOneField(on_delete='models.CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
