# Generated by Django 2.2.4 on 2019-11-05 01:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunomodel',
            name='data_nascimento',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 1, 20, 34, 935988, tzinfo=utc)),
        ),
    ]
