# Generated by Django 2.2.4 on 2020-02-25 21:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gerencia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidademodel',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 25, 21, 52, 22, 423638, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='colaboradormodel',
            name='dataNasc',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 25, 21, 52, 22, 424638, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='eventoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liberacao', models.CharField(choices=[('1', 'Ativo'), ('2', 'Bloqueado'), ('3', 'Inativo')], default=1, max_length=1)),
                ('titulo', models.CharField(blank=True, max_length=300, null=True)),
                ('descricao', models.CharField(blank=True, max_length=1000, null=True)),
                ('imageCapa', models.ImageField(blank=True, default='default.png', upload_to='')),
                ('dataEvento', models.DateTimeField(default=django.utils.timezone.now)),
                ('dataCadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete='models.CASCADE', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
