# Generated by Django 2.2.4 on 2019-11-05 03:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0003_auto_20191105_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunomodel',
            name='dataNasc',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 3, 30, 17, 529513, tzinfo=utc)),
        ),
    ]
