# Generated by Django 2.2.4 on 2019-11-10 20:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0006_auto_20191106_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunomodel',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='alunomodel',
            name='dataNasc',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 20, 34, 23, 84883, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='colaboradormodel',
            name='dataNasc',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 20, 34, 23, 87202, tzinfo=utc)),
        ),
    ]
