# Generated by Django 2.2.4 on 2019-11-11 00:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0007_auto_20191110_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='cidadeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('liberacao', models.CharField(choices=[('1', 'Ativa'), ('2', 'Bloqueada'), ('3', 'Inativa')], default=1, max_length=1)),
                ('nome', models.CharField(blank=True, max_length=300, null=True)),
                ('estado', models.CharField(choices=[('01', 'Acre (AC)'), ('02', 'Alagoas (AL)'), ('03', 'Amapá (AP)'), ('04', 'Amazonas (AM)'), ('05', 'Bahia (BA)'), ('06', 'Ceará (CE)'), ('07', 'Distrito Federal (DF)'), ('08', 'Espírito Santo (ES)'), ('09', 'Goiás (GO)'), ('10', 'Maranhão (MA)'), ('11', 'Mato Grosso (MT)'), ('12', 'Mato Grosso do Sul (MS)'), ('13', 'Minas Gerais (MG)'), ('14', 'Pará (PA)'), ('15', 'Paraíba (PB)'), ('16', 'Paraná (PR)'), ('17', 'Pernambuco (PE)'), ('18', 'Piauí (PI)'), ('19', 'Rio de Janeiro (RJ)'), ('20', 'Rio Grande do Norte (RN)'), ('21', 'Rio Grande do Sul (RS)'), ('22', 'Rondônia (RO)'), ('23', 'Roraima (RR)'), ('24', 'Santa Catarina (SC)'), ('25', 'São Paulo (SP)'), ('26', 'Sergipe (SE)'), ('27', 'Tocantins (TO)')], default=12, max_length=2)),
                ('dataCadastro', models.DateTimeField(default=datetime.datetime(2019, 11, 11, 0, 44, 26, 767193, tzinfo=utc))),
            ],
        ),
        migrations.RemoveField(
            model_name='classemodel',
            name='user',
        ),
        migrations.AlterField(
            model_name='alunomodel',
            name='dataNasc',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 0, 44, 26, 763283, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='classemodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='colaboradormodel',
            name='dataNasc',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 0, 44, 26, 765670, tzinfo=utc)),
        ),
    ]
