# Generated by Django 2.2.4 on 2019-11-11 02:03

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0008_auto_20191110_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunomodel',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='classemodel',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='colaboradormodel',
            name='estado',
        ),
        migrations.AlterField(
            model_name='alunomodel',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gerencia.cidadeModel'),
        ),
        migrations.AlterField(
            model_name='alunomodel',
            name='dataNasc',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 2, 3, 55, 403173, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cidademodel',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 2, 3, 55, 402314, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='classemodel',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='classemodel',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gerencia.cidadeModel'),
        ),
        migrations.AlterField(
            model_name='colaboradormodel',
            name='cep',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='colaboradormodel',
            name='cidade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gerencia.cidadeModel'),
        ),
        migrations.AlterField(
            model_name='colaboradormodel',
            name='dataNasc',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 2, 3, 55, 404458, tzinfo=utc)),
        ),
    ]
