# Generated by Django 2.2.4 on 2019-11-11 02:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0011_auto_20191110_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunomodel',
            name='dataNasc',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 2, 11, 23, 548858, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cidademodel',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 2, 11, 23, 548021, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cidademodel',
            name='liberacao',
            field=models.CharField(choices=[('1', 'Ativa'), ('2', 'Bloqueada'), ('3', 'Inativa')], default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='colaboradormodel',
            name='dataNasc',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 2, 11, 23, 550077, tzinfo=utc)),
        ),
    ]
