# Generated by Django 2.2.4 on 2019-11-11 02:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0012_auto_20191110_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunomodel',
            name='cidade',
            field=models.ForeignKey(on_delete='models.CASCADE', to='gerencia.cidadeModel'),
        ),
        migrations.AlterField(
            model_name='alunomodel',
            name='dataNasc',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 2, 14, 49, 272378, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cidademodel',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 2, 14, 49, 271461, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='classemodel',
            name='cidade',
            field=models.ForeignKey(default=1, on_delete='models.CASCADE', to='gerencia.cidadeModel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colaboradormodel',
            name='cidade',
            field=models.ForeignKey(default=1, on_delete='models.CASCADE', to='gerencia.cidadeModel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colaboradormodel',
            name='dataNasc',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 2, 14, 49, 274807, tzinfo=utc)),
        ),
    ]
