# Generated by Django 2.2.4 on 2019-11-11 02:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0017_auto_20191110_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunomodel',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='classemodel',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='colaboradormodel',
            name='cidade',
        ),
        migrations.AlterField(
            model_name='alunomodel',
            name='dataNasc',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 2, 21, 50, 148932, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cidademodel',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 2, 21, 50, 148123, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='colaboradormodel',
            name='dataNasc',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 2, 21, 50, 150050, tzinfo=utc)),
        ),
    ]
