# Generated by Django 2.2.4 on 2020-03-02 02:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0018_auto_20200301_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='respostaModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('resposta', models.CharField(blank=True, max_length=1000, null=True)),
                ('dataCadastro', models.DateTimeField(default=datetime.datetime(2020, 3, 2, 2, 48, 35, 760215, tzinfo=utc))),
            ],
        ),
        migrations.AlterField(
            model_name='cidademodel',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 2, 2, 48, 35, 747241, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='colaboradormodel',
            name='dataNasc',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 2, 2, 48, 35, 748237, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='perguntaModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.CharField(choices=[('1', 'Ativa'), ('2', 'Bloqueada'), ('3', 'Inativa')], default=1, max_length=1)),
                ('pergunta', models.CharField(blank=True, max_length=2000, null=True)),
                ('valor', models.CharField(blank=True, max_length=2, null=True)),
                ('dataCadastro', models.DateTimeField(default=datetime.datetime(2020, 3, 2, 2, 48, 35, 760714, tzinfo=utc))),
                ('respostas', models.ManyToManyField(blank=True, null=True, to='gerencia.respostaModel')),
            ],
        ),
    ]
