# Generated by Django 2.2.4 on 2020-03-05 10:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0021_auto_20200302_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perguntamodel',
            name='respostas',
        ),
        migrations.AddField(
            model_name='perguntamodel',
            name='respostaAlternativa1',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='perguntamodel',
            name='respostaAlternativa2',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='perguntamodel',
            name='respostaAlternativa3',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='perguntamodel',
            name='respostaCorreta',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='cidademodel',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 5, 10, 50, 1, 427467, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='colaboradormodel',
            name='dataNasc',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 5, 10, 50, 1, 427840, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='perguntamodel',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 5, 10, 50, 1, 429602, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='respostaModel',
        ),
    ]
