# Generated by Django 2.2.4 on 2019-11-11 16:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0022_auto_20191111_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunomodel',
            name='cidade',
            field=models.ForeignKey(default=1, on_delete='models.CASCADE', to='gerencia.cidadeModel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alunomodel',
            name='dataNasc',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 16, 1, 46, 806172, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cidademodel',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 16, 1, 46, 805175, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='colaboradormodel',
            name='dataNasc',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 16, 1, 46, 806172, tzinfo=utc)),
        ),
    ]
