# Generated by Django 2.2.4 on 2020-03-05 16:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0022_auto_20200305_0750'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perguntamodel',
            old_name='valor',
            new_name='pontuacao',
        ),
        migrations.AlterField(
            model_name='cidademodel',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 5, 16, 9, 41, 579445, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='colaboradormodel',
            name='dataNasc',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 5, 16, 9, 41, 579831, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='perguntamodel',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 5, 16, 9, 41, 581643, tzinfo=utc)),
        ),
    ]
