# Generated by Django 2.2.4 on 2019-11-11 16:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0024_auto_20191111_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alunomodel',
            old_name='cidade',
            new_name='teste',
        ),
        migrations.AlterField(
            model_name='alunomodel',
            name='dataNasc',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cidademodel',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 16, 8, 50, 843626, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='colaboradormodel',
            name='dataNasc',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 16, 8, 50, 844622, tzinfo=utc)),
        ),
    ]
