# Generated by Django 2.2.4 on 2020-03-06 12:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0025_auto_20200306_0901'),
    ]

    operations = [
        migrations.CreateModel(
            name='respostaModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('1', 'Correta'), ('2', 'Errada')], default=2, max_length=1)),
                ('resposta', models.CharField(blank=True, max_length=1000, null=True)),
                ('dataCadastro', models.DateTimeField(default=datetime.datetime(2020, 3, 6, 12, 57, 47, 956272, tzinfo=utc))),
            ],
        ),
        migrations.RenameField(
            model_name='perguntamodel',
            old_name='respostaAlternativa1',
            new_name='respostas',
        ),
        migrations.RemoveField(
            model_name='perguntamodel',
            name='respostaAlternativa2',
        ),
        migrations.RemoveField(
            model_name='perguntamodel',
            name='respostaAlternativa3',
        ),
        migrations.RemoveField(
            model_name='perguntamodel',
            name='respostaCorreta',
        ),
        migrations.AlterField(
            model_name='cidademodel',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 6, 12, 57, 47, 954173, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='colaboradormodel',
            name='dataNasc',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 6, 12, 57, 47, 954547, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='perguntamodel',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 6, 12, 57, 47, 956569, tzinfo=utc)),
        ),
    ]
