# Generated by Django 2.2.4 on 2019-11-11 16:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0025_auto_20191111_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunomodel',
            name='teste',
            field=models.ForeignKey(default=1, on_delete='models.CASCADE', to='gerencia.cidadeModel'),
        ),
        migrations.AlterField(
            model_name='cidademodel',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 16, 11, 36, 45804, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='colaboradormodel',
            name='dataNasc',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 16, 11, 36, 46832, tzinfo=utc)),
        ),
    ]
