# Generated by Django 2.2.4 on 2020-03-06 12:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0026_auto_20200306_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidademodel',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 6, 12, 58, 20, 582345, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='colaboradormodel',
            name='dataNasc',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 6, 12, 58, 20, 582709, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='perguntamodel',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 6, 12, 58, 20, 584760, tzinfo=utc)),
        ),
        migrations.RemoveField(
            model_name='perguntamodel',
            name='respostas',
        ),
        migrations.AddField(
            model_name='perguntamodel',
            name='respostas',
            field=models.ManyToManyField(to='gerencia.respostaModel'),
        ),
        migrations.AlterField(
            model_name='respostamodel',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 6, 12, 58, 20, 584457, tzinfo=utc)),
        ),
    ]
