# Generated by Django 2.2.4 on 2019-11-11 16:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0026_auto_20191111_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunomodel',
            name='teste',
            field=models.ForeignKey(default='', on_delete='models.CASCADE', to='gerencia.cidadeModel'),
        ),
        migrations.AlterField(
            model_name='cidademodel',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 16, 12, 1, 195596, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='colaboradormodel',
            name='dataNasc',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 16, 12, 1, 196596, tzinfo=utc)),
        ),
    ]
