# Generated by Django 2.2.4 on 2019-11-11 16:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0027_auto_20191111_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunomodel',
            name='teste',
            field=models.ForeignKey(on_delete='models.CASCADE', to='gerencia.cidadeModel'),
        ),
        migrations.AlterField(
            model_name='cidademodel',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 16, 13, 6, 944117, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='cidademodel',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='colaboradormodel',
            name='dataNasc',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 16, 13, 6, 945120, tzinfo=utc)),
        ),
    ]
