# Generated by Django 2.2.4 on 2019-11-11 18:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0032_auto_20191111_1536'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='classeModel',
            new_name='salaModel',
        ),
        migrations.AlterField(
            model_name='cidademodel',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 18, 39, 6, 438581, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='colaboradormodel',
            name='dataNasc',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 18, 39, 6, 439579, tzinfo=utc)),
        ),
    ]
