# Generated by Django 2.2.4 on 2019-11-11 18:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0034_auto_20191111_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='alunomodel',
            name='salaAula',
            field=models.ForeignKey(default=1, on_delete='models.CASCADE', to='gerencia.salaModel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cidademodel',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 18, 41, 39, 859304, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='colaboradormodel',
            name='dataNasc',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 11, 18, 41, 39, 859304, tzinfo=utc)),
        ),
    ]
