# Generated by Django 2.2.4 on 2020-03-16 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0008_auto_20200226_0027'),
        ('gerencia', '0049_auto_20200312_0806'),
    ]

    operations = [
    ]
