# Generated by Django 2.2.4 on 2019-09-28 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('visualizacao', models.CharField(choices=[('1', 'Não Visualizado'), ('2', 'visualizado')], default=1, max_length=1)),
                ('nome', models.CharField(max_length=200)),
                ('sobrenome', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(max_length=150)),
                ('telefone', models.CharField(blank=True, max_length=300, null=True)),
                ('mensagem', models.CharField(max_length=500)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
