# Generated by Django 2.2.4 on 2019-12-10 03:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20191001_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='indicacao',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('visualizacao', models.CharField(choices=[('1', 'Não Visualizado'), ('2', 'visualizado')], default=1, max_length=1)),
                ('nome', models.CharField(max_length=200)),
                ('sobrenome', models.CharField(blank=True, max_length=200, null=True)),
                ('empresa', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('telefone', models.CharField(blank=True, max_length=14, null=True)),
                ('mensagem', models.CharField(blank=True, max_length=500, null=True)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
