# Generated by Django 2.2.4 on 2020-03-10 12:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0039_auto_20200310_0910'),
        ('website', '0004_testenivelamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='respostaNivelamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('pergunta', models.ForeignKey(on_delete='models.CASCADE', to='gerencia.perguntaModel')),
                ('resposta', models.ForeignKey(on_delete='models.CASCADE', to='gerencia.respostaModel')),
            ],
        ),
    ]
