# Generated by Django 2.2.4 on 2020-03-10 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_respostanivelamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='testenivelamento',
            name='respostas',
            field=models.ManyToManyField(to='website.respostaNivelamento'),
        ),
    ]
