# Generated by Django 2.2.4 on 2019-10-29 03:33

import cloudinary.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0002_auto_20191027_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventomodel',
            name='name',
        ),
        migrations.AddField(
            model_name='eventomodel',
            name='conteudo',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='eventomodel',
            name='data_cadastro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='eventomodel',
            name='data_evento',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='eventomodel',
            name='data_publicacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='eventomodel',
            name='descricao',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='eventomodel',
            name='imagem_capa',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255, verbose_name='imagem_capa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='eventomodel',
            name='titulo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='eventomodel',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
