# Generated by Django 2.2.4 on 2019-12-10 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0041_auto_20191111_1541'),
        ('evento', '0029_auto_20191117_2042'),
    ]

    operations = [
    ]
