# Generated by Django 2.2.4 on 2020-02-25 22:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0046_auto_20200225_1852'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
        migrations.RemoveField(
            model_name='eventomodel',
            name='data_cadastro',
        ),
        migrations.RemoveField(
            model_name='eventomodel',
            name='data_evento',
        ),
        migrations.RemoveField(
            model_name='eventomodel',
            name='data_publicacao',
        ),
        migrations.RemoveField(
            model_name='eventomodel',
            name='imagem',
        ),
        migrations.RemoveField(
            model_name='eventomodel',
            name='imagem_capa',
        ),
        migrations.AddField(
            model_name='eventomodel',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 25, 22, 5, 29, 928900, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='eventomodel',
            name='dataEvento',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 25, 22, 5, 29, 928900, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='eventomodel',
            name='imagem1',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='eventomodel',
            name='imagem10',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='eventomodel',
            name='imagem2',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='eventomodel',
            name='imagem3',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='eventomodel',
            name='imagem4',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='eventomodel',
            name='imagem5',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='eventomodel',
            name='imagem6',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='eventomodel',
            name='imagem7',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='eventomodel',
            name='imagem8',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='eventomodel',
            name='imagem9',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
        migrations.AddField(
            model_name='eventomodel',
            name='imagemCapa',
            field=models.ImageField(blank=True, default='default.png', upload_to=''),
        ),
    ]
