# Generated by Django 2.2.4 on 2020-02-25 23:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0048_auto_20200225_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventomodel',
            name='dataCadastro',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 25, 23, 47, 26, 709866, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventomodel',
            name='dataEvento',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 25, 23, 47, 26, 709866, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventomodel',
            name='imagem1',
            field=models.ImageField(blank=True, default='media/default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eventomodel',
            name='imagem10',
            field=models.ImageField(blank=True, default='media/default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eventomodel',
            name='imagem2',
            field=models.ImageField(blank=True, default='media/default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eventomodel',
            name='imagem3',
            field=models.ImageField(blank=True, default='media/default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eventomodel',
            name='imagem4',
            field=models.ImageField(blank=True, default='media/default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eventomodel',
            name='imagem5',
            field=models.ImageField(blank=True, default='media/default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eventomodel',
            name='imagem6',
            field=models.ImageField(blank=True, default='media/default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eventomodel',
            name='imagem7',
            field=models.ImageField(blank=True, default='media/default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eventomodel',
            name='imagem8',
            field=models.ImageField(blank=True, default='media/default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eventomodel',
            name='imagem9',
            field=models.ImageField(blank=True, default='media/default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='eventomodel',
            name='imagemCapa',
            field=models.FileField(null=True, upload_to='media/', verbose_name=''),
        ),
    ]
