# Generated by Django 2.2.4 on 2019-11-04 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aluno', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='alunoModel',
        ),
    ]
