# Generated by Django 2.2.4 on 2019-10-29 03:52

import cloudinary.models
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0003_auto_20191029_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventomodel',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 3, 52, 59, 68333, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventomodel',
            name='data_evento',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 3, 52, 59, 68307, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventomodel',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 29, 3, 52, 59, 68271, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventomodel',
            name='imagem',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='eventos/imagem'),
        ),
        migrations.AlterField(
            model_name='eventomodel',
            name='imagem_capa',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='eventos/imagem_capa'),
        ),
    ]
