# Generated by Django 2.2.4 on 2020-02-29 17:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0056_auto_20200229_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventomodel',
            name='hora_evento',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventomodel',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 29, 17, 19, 18, 465033, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventomodel',
            name='data_evento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventomodel',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 29, 17, 19, 18, 465033, tzinfo=utc)),
        ),
    ]
