# Generated by Django 2.2.4 on 2020-03-02 00:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('evento', '0057_auto_20200229_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventomodel',
            name='data_cadastro',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 2, 0, 47, 38, 170437, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='eventomodel',
            name='data_publicacao',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 2, 0, 47, 38, 169938, tzinfo=utc)),
        ),
    ]
